.gitignore, README.md, config-EXAMPLE.json
README.md - added more info about the config file
Config.json - renamed to **Config-EXAMPLE.json** and edited readme to relect that
=> Updated README.md and Config.json

src/contracts/helperFunctions.js, src/minecraft/commands/dailyCommand.js, src/minecraft/commands/monthlyCommand.js, src/minecraft/commands/weeklyCommand.js
Removal of "/v1" in every path
=> Pixelic-API Future proofing

src/contracts/helperFunctions.js, src/minecraft/commands/dailyCommand.js, src/minecraft/commands/monthlyCommand.js, src/minecraft/commands/weeklyCommand.js
Future proofed the daily/weekly/monthly paths as they will now be formatted like /player/pixelic/daily instead of /player/daily/pixelic which for other paths continues to make them longer and longer like /player/historical/all/pixelic which now is only /player/pixelic/all. In addition to that I also fixed your register requests + added the corresponding reply for the 409 error code.
=> [Pixelic-API] Path Changes + Register Fix

Dockerfile, README.md
- This adds a generic Dockerfile built for NodeJS.
- It also updates the README file with instructions on how to setup docker.
=> Add Dockerfile and full readme instructions for docker setup

config.example.json, src/discord/commands/blacklistCommand.js, src/discord/commands/demoteCommand.js, src/discord/commands/executeCommand.js, src/discord/commands/infoCommand.js, src/discord/commands/inviteCommand.js, src/discord/commands/kickCommand.js, src/discord/commands/muteCommand.js, src/discord/commands/promoteCommand.js, src/discord/commands/purgeCommand.js, src/discord/commands/unmuteCommand.js, src/discord/events/interactionCreate.js
- Adds a toggle to allow for single-role override of officer commands.
- Disables `web` by default.
=> Default to discord integration permission handling

README.md, config.example.json, package.json, src/minecraft/handlers/ChatHandler.js
Make it go to limbo and not spam debug
=> add Limbo options and update skyhelper-networth

src/minecraft/commands/boopCommand.js
tested
!boop (username)
will boop the player
and say who booped them
has a 5min cooldown
=> boop command

src/minecraft/commands/dinosaurCommand.js, src/minecraft/commands/rabbitCommand.js
rabbit requested by soupy
dino requested by rex
=> rabbit + dino command

src/discord/handlers/MessageHandler.js
(i.e. leaking and ip address)
resolves #240
=> (Hopefully) prevent bot being muted due to unfortunate wording

src/minecraft/other/eventNotifier.js
This PR changes the Text for Event Notifications to not look like they look right now.
Event starting in x minutes: 5m -> Starting in 5m!
Event starting now: NOW -> Starting now!
Also hello Ducky
=> small text change to event notifier

src/minecraft/handlers/ChatHandler.js
hypixel patched the way to get into limbo and added there own /limbo
=> autolimbo fix

src/minecraft/handlers/ChatHandler.js
=> fix weight in join

src/minecraft/handlers/ChatHandler.js
=> Fix Updating Guild Status

src/minecraft/commands/warpoutCommand.js
Credit: [#27](https://github.com/Wristspasm/Wristspasm-Discord-Bot/pull/27) from @CatboyDark
=> Adjust Phrasing of !warpout

.eslintrc, src/discord/DiscordManager.js, src/minecraft/commands/auctionHouseCommand.js, src/minecraft/commands/chickenCommand.js, src/minecraft/commands/dinosaurCommand.js, src/minecraft/commands/duckCommand.js, src/minecraft/commands/kittyCommand.js, src/minecraft/commands/picketCommand.js, src/minecraft/commands/rabbitCommand.js, src/minecraft/commands/raccoonCommand.js, src/minecraft/commands/renderArmorCommand.js, src/minecraft/commands/renderEquipmentCommand.js, src/minecraft/commands/renderItemsCommand.js, src/minecraft/commands/renderPetCommand.js
=> Imgur Url "fix"

src/minecraft/commands/PlayerCommand.js
=> Player Command

API/stats/talismans.js
Fix talismans when player has never gone to rift
=> fix !talismans

API/functions/getLatestProfile.js, API/stats/hotm.js, src/minecraft/commands/forgeCommand.js, src/minecraft/commands/hotmCommand.js, src/minecraft/commands/skyblockCommand.js
TLDR This stops some commands from working because Hypixel added a ratelimit on fetching the same player's stats every ~30 seconds or something. This player stats section is only used in one datapoint so i don't see a point in keeping it
=> Remove Small API Request

src/discord/commands/blacklistCommand.js, src/minecraft/handlers/ChatHandler.js
At somepoint hypixel made a change making it so /ignore and or /block cannot be ran from limbo. This warps the bot out of limbo then warps it back into limbo after the user has been blocked.
=> Fix blacklist

config.example.json, src/discord/commands/requirementsCommand.js, src/discord/events/interactionCreate.js, src/minecraft/handlers/ChatHandler.js
- Added a requirements command that uses the already built requirement checker
- Made requirement checker pull data only from one source
- Added an accept button for members requesting to join the guild
**Command doesn't work - Check #290 explaining fetching same person twice issue**
Requires #290 to be merged first
=> Requirements Command

src/discord/commands/updateCommand.js
/update was unable to find the functions after new update
Also fixed it not fully working with level roles
Also fixed some of the changed stat names
=> fix(/update): Unable to find functions
